version: '3.8'

# nginx + certbot 웹서버 인프라
# 이 파일은 인프라 서비스만 포함합니다.
# 웹서비스들은 별도 프로젝트에서 관리됩니다.

services:
  # nginx 웹서버
  nginx:
    build:
      context: ../nginx
      dockerfile: Dockerfile
    container_name: nginx-infra
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../nginx/conf.d:/etc/nginx/conf.d:ro
      - ../certbot/conf:/etc/letsencrypt:ro
      - ../certbot/www:/var/www/certbot:ro
      - nginx_logs:/var/log/nginx
    restart: unless-stopped
    networks:
      - web-services-network

  # certbot SSL 인증서 관리
  certbot:
    build:
      context: ../certbot
      dockerfile: Dockerfile
    container_name: certbot-infra
    volumes:
      - ../certbot/conf:/etc/letsencrypt
      - ../certbot/www:/var/www/certbot
      - ../certbot/logs:/var/log
    environment:
      - CERTBOT_DOMAIN=${CERTBOT_DOMAIN}
      - CERTBOT_EMAIL=${CERTBOT_EMAIL}
      - CERTBOT_STAGING=${CERTBOT_STAGING}
    restart: unless-stopped
    networks:
      - web-services-network

volumes:
  nginx_logs:
    driver: local

networks:
  web-services-network:
    driver: bridge
    external: false
